/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet2_labyrinthe_francois_thomas_lelevreur;

import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.ImageObserver;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Tanguy
 */
public class FenetreAccueil extends javax.swing.JFrame {

    JPanel btnJouers;

    /**
     * Creates new form FenetreAccueil
     */
    public FenetreAccueil() {

        initComponents();
        Image image = new ImageIcon(getClass().getResource("/images/accueil.png")).getImage();
        Image imageRedimenssionne = image.getScaledInstance(1000, 1000, Image.SCALE_SMOOTH);

        Image imageADessiner = new ImageIcon(imageRedimenssionne).getImage();
        JLayeredPane layeredPane = new JLayeredPane() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(imageADessiner, 0, 0, 640, 640, (ImageObserver) this);
            }
        };
        layeredPane.setBounds(0, 0, 1200, 1200);
        add(layeredPane);

        
            int y = 87;
            btnJouers = new JPanel();
            
            btnJouers.setLayout(new GridLayout(1, 1));// Les valeurs RGB pour le bleu marine peuvent varier

            btnJouers.setBounds(205, 225 +  y, 210, 40);
            

            JButton UnJoueur = new JButton();
            btnJouers.setOpaque(false);
            

            UnJoueur.setBounds(0, 0, 200, 100);
           
            ActionListener ecouteur = new ActionListener() {
            
                @Override
                public void actionPerformed(ActionEvent e) {

                    new PlateauGraphique(1).setVisible(true);

                    setVisible(false);

                    repaint();

                }
            };
            UnJoueur.addActionListener(ecouteur);
            btnJouers.add(UnJoueur);
            JButton DeuxJoueurs = new JButton();
            btnJouers.setOpaque(false);
            

            DeuxJoueurs.setBounds(0, 0, 200+y, 100);
           
            ActionListener deuxjoueurs = new ActionListener() {
            
                @Override
                public void actionPerformed(ActionEvent e) {

                    new PlateauGraphique(2).setVisible(true);

                    setVisible(false);

                    repaint();

                }
            };
            DeuxJoueurs.addActionListener(deuxjoueurs);
            btnJouers.add(DeuxJoueurs);
            JButton TroisJoueur = new JButton();
            btnJouers.setOpaque(false);
            

            TroisJoueur.setBounds(0, 0, 200+2*y, 100);
           
            ActionListener troisjoueurs = new ActionListener() {
            
                @Override
                public void actionPerformed(ActionEvent e) {

                    new PlateauGraphique(3).setVisible(true);

                    setVisible(false);

                    repaint();

                }
            };
            TroisJoueur.addActionListener(troisjoueurs);
            btnJouers.add(TroisJoueur);
            layeredPane.add(btnJouers);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
